services:
  mysql:
    build:
      dockerfile: Dockerfile-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passisnotgood
      MYSQL_DATABASE: candh
      MYSQL_USER: candh
      MYSQL_PASSWORD: passisnotgood
    ports:
      - "3306:3306"

  apache:
    build:
      dockerfile: Dockerfile
    restart: always
    links:
      - mysql
    environment:
      TZ: 'America/New_York'
    ports:
      - "8080:80"